name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - playground

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
      - name: 'install packages'
        run: composer dump-autoload
        working-directory: ./src
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
