name: Qodana
on:
  workflow_dispatch:
  push:
    branches:
      - playground
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Docker Pull'
        run: |
          docker pull jetbrains/qodana-php
      - name: 'Qodana Scan'
        run: |
          docker run --rm \
          -v /:/data/project/ \
          -e QODANA_TOKEN=${{ secrets.QODANA_TOKEN }} \
          -e QODANA_BRANCH=${{ github.ref }} \
          -e QODANA_REVISION=${{ github.sha }} \
          -e QODANA_JOB_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID} \
          jetbrains/qodana-php
